### ISSUE TITLE
initial position

### ISSUE THREAD

**Issue by drcmda** [birkir/react-three-gui#1]
would it mean much trouble to allow us to either position by passing in styles, or predefined slots (top/left, bottom/right, center, etc) ? dragging is fine, it's just about the startup position.

**Comment by birkir** [comment]
I'll add this, also persist the position with localStorage.

**Comment by szemy2** [comment]
This would be great! Is there a way to monkeypatch it while you add it? I tried overwriting styles but couldn't get it to work.

**Comment by birkir** [comment]
This feature is shipped with v0.3.1
