### ISSUE TITLE
Adding a step prop for number inputs

### ISSUE THREAD

**Issue by gsimone** [birkir/react-three-gui#16]
Hi, I find myself reaching for int numbers of multiples, mimicking the step attribute for input[type="range"] would help a lot.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range

If you agree I can try and PR the change!

EDIT: if somebody finds this, this is how I worked around it:

```jsx
function useIntControl(name, { value, ...opts }) {

  const [intVal, setVal] = React.useState(value)

  const setIntVal = React.useCallback(val => { setVal(parseInt(val, 10)) }, [setVal])
  
  useControl(name, { type: "number", value: intVal, ...opts, state: [intVal, setIntVal] })
  
  return intVal

}

useIntControl("FPS", { value: 24, max: 120 })
```

**Comment by birkir** [comment]
I am not sure what you are achieving with this, what problem did you have before? Whats the difference between this and just using `useControl('FPS', { type: 'number', max: 120, value: 24 })`?

**Comment by snsie** [comment]
Thank you for including your work around. Adding a property to enable a configurable step size would be a helpful addition. Having the option to specify a number type (e.g. int or float) would be nice as well. If a user specifies an 'int' type then the GUI could be configured to not display the decimal places.  This would be useful in situations when the property you are controlling doesn't accept numbers with decimals. For example, setting the number of iterations that a shader should run might result in an error if it is expecting a whole number.

**Comment by cedeber** [comment]
Hello. I also would like to reopen this issue. Sometimes you want integer, sometimes you want to navigate between 0 and 1 with very high precision. Would be nice to have this option.
Thanks.
