### ISSUE TITLE
Unable to use react-three-gui with custom `Canvas` wrapper.

### ISSUE THREAD

**Issue by Honga1** [birkir/react-three-gui#23]
## What
Unable to use react-three-gui with custom `Canvas` wrapper.

## Demo
See the code sandbox and code snippets below. You'll note that the Y control element is not being added.

## Possible causes
Context is not being passed deep into DOM tree. This could be related to: https://github.com/react-spring/react-three-fiber/issues/43

## Possible work arounds
Export ControlsContext so that we can forward the context ourselves as shown here: https://codesandbox.io/s/react-three-fiber-react-spring-91uuc?file=/src/index.js:1605-1613 

## Considerations
You could think about using `zustand` for doing context/state management for the plugin. Although it's not vanilla react it suits your hook model well.

## Examples of issue
See: [Here](https://codesandbox.io/s/react-three-fiber-gui-forked-92xrv?file=/src/index.tsx)

```TSX
import React from 'react';
import { render } from 'react-dom';
import { Canvas } from 'react-three-fiber';
import { ControlsProvider, Controls, useControl } from 'react-three-gui';

function AddXControl() {
  const posX = useControl('Pos X', { type: 'number', spring: true });
  return <></>;
}

function AddYControl() {
  // This control never gets added
  const posY = useControl('Pos Y', { type: 'number', spring: true });
  return <></>;
}

export const AbstractedCanvas = ({
  children,
}: React.PropsWithChildren<{}>): React.ReactElement => {
  return <Canvas>{children}</Canvas>;
};

function App() {
  return (
    <ControlsProvider>
      <Canvas>
        <AddXControl />
      </Canvas>

      <AbstractedCanvas>
        <AddYControl />
      </AbstractedCanvas>

      <Controls />
    </ControlsProvider>
  );
}

render(<App />, document.querySelector('#root'));
```

It seems that your `ControlsProvider` is only providing context one level into the DOM tree.

**Comment by brianzinn** [comment]
Ran into the same issue and needed to export the `ControlsContext`:
https://github.com/birkir/react-three-gui/pull/22/files#diff-d83655eeed6aa9d9e8a6b2034d603328R183

As a temporary workaround you can add to src/index.ts:
```
export { ControlsContext, IControlsContext } from './contexts/controls-context'
```
then `yarn link`.

**Comment by AndrewPrifer** [comment]
Relevant info, for some reason, the [codesandbox](https://codesandbox.io/s/react-three-fiber-gui-62pvp) linked in the readme works, but only as long as `ControlsProvider` and `Canvas` are in the same component. As soon as the canvas component is factored into a different component, it breaks too ([codesandbox](https://codesandbox.io/s/react-three-fiber-gui-forked-tken1?file=/src/index.tsx)).

**Comment by brianzinn** [comment]
@AndrewPrifer I think that's because you need to bridge the provider across the render boundary.  Have a look here:
https://github.com/birkir/react-three-gui/pull/22/files#diff-db9230e3ea687f101161ccd3e80a946357a3a2bf456db3cce45f77e829035f38R182

In other words, the provider won't pass context through from ReactDOM renderer to R3R, so you need to do so yourself.

**Comment by AndrewPrifer** [comment]
@brianzinn thank you, I understand that already, I was simply pointing it out to those who are puzzled by why the example in the README works, while their code doesn't (happened to me 😉).

**Comment by birkir** [comment]
I have now changed the API. Please take a look.

**Comment by AndrewPrifer** [comment]
@birkir I took a look at the API. I think the context bridge helpers `withControls` and `Controls.Canvas` are a bit superfluous, `drei` already has a [context bridge utility](https://github.com/pmndrs/drei#usecontextbridge) the only thing missing from `react-three-gui` in this regard was an export of the controls context.

I still think though that for ultimate developer convenience, `zustand` would be the ideal solution. It is already used all across react-three-fiber and drei, so it wouldn't even be an extra dependency for r3f users. As for the global state problem that you mentioned in the other issue, it can be solved by just instantiating multiple zustand stores.

**Comment by birkir** [comment]
Cool thanks for the tip about drei's context bridge utility. Didn't know about that, doesn't solve all of the problem through.

```tsx
// this would not work because the contextbridge won't have
// access to the context *after* the controls provider.
export function App () {
  const ContextBridge = useContextBridge(ControlsContext);
  return (
    <ControlsProvider>
      <Canvas>
        <ContextBridge>
          <Scene />
        </ContextBridge>
      </Canvas>
    </ControlsProvider>
  );
}
```

But back to the other point, how would using a different technology to handle state help with developer convenience? Just to be able to skip the context bridging, then we would be back to hot reload issues.

And with all due respect to `zustand`, I'm a fan of MST (hope you get where I'm going with this).

**Comment by AndrewPrifer** [comment]
> // this would not work because the contextbridge won't have
> // access to the context *after* the controls provider.

That is true, the provider has to precede the call to `useContextBridge`. The solution would be to place the `ControlsProvider` above in the hierarchy, but I understand if it seems a little cumbersome to you.

> But back to the other point, how would using a different technology to handle state help with developer convenience? Just to be able to skip the context bridging, then we would be back to hot reload issues.

The way it would help is that it can cross renderer boundaries, unlike context, for which we need workarounds, like the one you included, or the one `drei` does. My emphasis was not really on `zustand`, but on not using context. The reason I suggested this library specifically is because it is explicitly named in the ecosystem section of r3f, and @drcmda also suggests the use of `zustand` when working with r3f in cases where we would otherwise use context, since it was specifically developed as a lightweight solution with that use case in mind. I do however understand if you have an aversion to including extra dependencies, and I'm not married to it either (big MST fan too btw, but I think in this case its sheer size would preclude it from the possible alternatives 😉)

**Comment by Honga1** [comment]
@birkir Thank you for the update! My requirement has ceased however. I'm hands off from this issue from herein. If you think that it is closed please go ahead and close it.

I enjoyed the discussion to this point :).

**Comment by Honga1** [comment]
I believe this is now no longer relevant with the 0.40 changes mentioned here:

https://github.com/birkir/react-three-gui/issues/23#issuecomment-712753037

Closing for now.
