### ISSUE TITLE
Value changes trigger constant re-renders

### ISSUE THREAD

**Issue by mattrossman** [birkir/react-three-gui#27]
[I forked the example sandbox](https://codesandbox.io/s/react-three-fiber-gui-forked-tls4s) and added
```
console.log('render')
```
on line 49. When adjusting values in the GUI, that gets printed on each frame indicating that the component is constantly re-rendering. Since this is based on `react-spring`, this is surprising to me since spring can animate values without triggering constant re-renders.

I can't tell if this is expected but it seems like a performance bug.

**Comment by birkir** [comment]
Fixed, but this is expected to happen when you don't have a spring value.
