### ISSUE TITLE
Controls modal empty in Gatsby environment

### ISSUE THREAD

**Issue by arnespremberg** [birkir/react-three-gui#31]
Hi there,

I'm not sure whether I'm missing out on something (like this generally wouldn't work) or if the issue is related to a bug. I'm running a React component in a Gatsby Environment, however the Controls Modal seems to have no content.

See the simplified component code here:
```
import React, { useRef, useState } from 'react'
import { extend, Canvas, useThree, useFrame } from 'react-three-fiber'
import { Controls, useControl } from 'react-three-gui';

export default props => {

    const rotationX = useControl('Rotation X', { type: 'number' });

    return (
        <Controls.Provider>
            <Controls.Canvas>
            <mesh rotation-x={rotationX} />
            </Controls.Canvas>
            <Controls />
        </Controls.Provider>
    )
}
```

See the resulting modal (opened) here:
<img width="396" alt="Screenshot 2020-12-10 at 16 26 39" src="https://user-images.githubusercontent.com/52531560/101792153-ab9c7e80-3b04-11eb-884f-906a119ac85c.png">

See the contents of the modal here, screenshot from Chrome inspector:
<img width="329" alt="Screenshot 2020-12-10 at 16 27 03" src="https://user-images.githubusercontent.com/52531560/101792210-beaf4e80-3b04-11eb-9203-c82208c508d4.png">

Any help is much appreciated!
Thanks,
Arne

**Comment by birkir** [comment]
The `useControl` will have to be **inside** the provider

```jsx
import React, { useRef, useState } from 'react'
import { extend, Canvas, useThree, useFrame } from 'react-three-fiber'
import { Controls, useControl } from 'react-three-gui';

function MyComponent() {
  const rotationX = useControl('Rotation X', { type: 'number' });
  return <mesh rotation-x={rotationX} />;
}

export default props => {
  return (
    <Controls.Provider>
      <Controls.Canvas>
        <MyComponent />
      </Controls.Canvas>
      <Controls />
    </Controls.Provider>
  );
}
```

**Comment by arnespremberg** [comment]
Thanks for the fast reply! It's working now...
