### ISSUE TITLE
Hierachy of component issue

### ISSUE THREAD

**Issue by Fasani** [birkir/react-three-gui#7]
This is perhaps not an issue but could be outlined in the docs.

I just experienced this problem where if I put `<Controls>` above my `<Canvas>` I could not interact with it. I could not move sliders or drag and move the controls around.  
Is this a known thing? Can we add it to the docs?

This is ok:
<img width="271" alt="Screenshot 2020-06-01 at 22 25 20" src="https://user-images.githubusercontent.com/448410/83451292-f1da9c00-a456-11ea-9173-1baedd27a088.png">

This is not:
<img width="275" alt="Screenshot 2020-06-01 at 22 25 09" src="https://user-images.githubusercontent.com/448410/83451313-f99a4080-a456-11ea-8176-9ce6f29c41dc.png">

**Comment by birkir** [comment]
This should be fixed with v0.3
